export const jackson: string
export const pop: string
export const memphis: string
export const slo: string
export const nyc: string
export const jackToMem: string
export const draw: string
export const memToSlo: string
export const sloToNyc: string
export const appear: string
